# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/presto_parser/all/presto_parser.rbi
#
# presto_parser-1.0.0

module PrestoParser
end
class PrestoParser::Visitor
  def accept(input); end
  def parse(input); end
  def visit(context); end
  def visit_aliased_relation(context); end
  def visit_arithmetic_binary(context); end
  def visit_arithmetic_unary(context); end
  def visit_array_constructor(context); end
  def visit_at_time_zone(context); end
  def visit_back_quoted_identifier(context); end
  def visit_base_type(context); end
  def visit_between(context); end
  def visit_binary_literal(context); end
  def visit_boolean_default(context); end
  def visit_boolean_literal(context); end
  def visit_boolean_value(context); end
  def visit_bounded_frame(context); end
  def visit_cast(context); end
  def visit_children(context); end
  def visit_column_aliases(context); end
  def visit_column_definition(context); end
  def visit_column_reference(context); end
  def visit_comparison(context); end
  def visit_comparison_operator(context); end
  def visit_comparison_quantifier(context); end
  def visit_concatenation(context); end
  def visit_cube(context); end
  def visit_current_row_bound(context); end
  def visit_decimal_literal(context); end
  def visit_dereference(context); end
  def visit_digit_identifier(context); end
  def visit_distinct_from(context); end
  def visit_exists(context); end
  def visit_explain_format(context); end
  def visit_explain_type(context); end
  def visit_expression(context); end
  def visit_extract(context); end
  def visit_filter(context); end
  def visit_function_call(context); end
  def visit_group_by(context); end
  def visit_grouping_element(context); end
  def visit_grouping_expressions(context); end
  def visit_grouping_set(context); end
  def visit_in_list(context); end
  def visit_in_subquery(context); end
  def visit_inline_table(context); end
  def visit_integer_literal(context); end
  def visit_interval(context); end
  def visit_interval_field(context); end
  def visit_interval_literal(context); end
  def visit_isolation_level(context); end
  def visit_join_criteria(context); end
  def visit_join_relation(context); end
  def visit_join_type(context); end
  def visit_lambda(context); end
  def visit_like(context); end
  def visit_like_clause(context); end
  def visit_logical_binary(context); end
  def visit_logical_not(context); end
  def visit_multiple_grouping_sets(context); end
  def visit_named_argument(context); end
  def visit_named_query(context); end
  def visit_non_reserved(context); end
  def visit_normal_form(context); end
  def visit_normalize(context); end
  def visit_null_literal(context); end
  def visit_null_predicate(context); end
  def visit_numeric_literal(context); end
  def visit_over(context); end
  def visit_parameter(context); end
  def visit_parenthesized_expression(context); end
  def visit_parenthesized_relation(context); end
  def visit_position(context); end
  def visit_positional_argument(context); end
  def visit_predicated(context); end
  def visit_privilege(context); end
  def visit_qualified_name(context); end
  def visit_quantified_comparison(context); end
  def visit_query(context); end
  def visit_query_no_with(context); end
  def visit_query_primary(context); end
  def visit_query_specification(context); end
  def visit_query_term_default(context); end
  def visit_quoted_identifier(context); end
  def visit_quoted_identifier_alternative(context); end
  def visit_read_committed(context); end
  def visit_read_uncommitted(context); end
  def visit_relation_default(context); end
  def visit_repeatable_read(context); end
  def visit_rollup(context); end
  def visit_row_constructor(context); end
  def visit_sample_type(context); end
  def visit_sampled_relation(context); end
  def visit_searched_case(context); end
  def visit_select_item(context); end
  def visit_serializable(context); end
  def visit_set_operation(context); end
  def visit_set_quantifier(context); end
  def visit_simple_case(context); end
  def visit_single_grouping_set(context); end
  def visit_sort_item(context); end
  def visit_special_date_time_function(context); end
  def visit_string_literal(context); end
  def visit_subquery(context); end
  def visit_subquery_expression(context); end
  def visit_subquery_relation(context); end
  def visit_subscript(context); end
  def visit_substring(context); end
  def visit_table(context); end
  def visit_table_element(context); end
  def visit_table_name(context); end
  def visit_table_properties(context); end
  def visit_table_property(context); end
  def visit_time_zone_interval(context); end
  def visit_time_zone_string(context); end
  def visit_transaction_access_mode(context); end
  def visit_type(context); end
  def visit_type_constructor(context); end
  def visit_type_parameter(context); end
  def visit_unbounded_frame(context); end
  def visit_unnest(context); end
  def visit_unquoted_identifier(context); end
  def visit_value_expression(context); end
  def visit_when_clause(context); end
  def visit_window_frame(context); end
  def visit_with(context); end
end
class PrestoParser::Visitor::UnrecognizedContextError < StandardError
end
